### ISSUE TITLE
Filter option for many signals

### ISSUE THREAD

**Issue by mguthaus** [StefanSchippers/xschem-gaw#1]
If you open a file with many signals, it is difficult to find them in the signal list window. Is it possible to add a regex filter at the top and only show the remaining signals?

**Comment by StefanSchippers** [comment]
Hi, Matt.

I have to check if i am able to do this.
What i did with gaw was to set up a minimal integration with xschem, for example [send waveforms to gaw](https://xschem.sourceforge.io/stefan/xschem_man/video_tutorials/probe_to_gaw.mp4) by highlighting nets in xschem.
The 'talk to gaw' protocol over tcp is documented so it was easy to integrate ( i added some features in gaw to make it work better).
I know the signal list is way too primitive, without a search filter. 
However the original author is (almost) no more working on gaw. This was the reason i forked gaw into xschem-gaw
I will take a look, may be i can find the relevant pieces of code and make this addition. But i don't know the needed effort right now...

**Comment by StefanSchippers** [comment]
Sorry, Matt i didn't see there was already a pull req. ready. 
Works great, Thanks!
