### ISSUE TITLE
Compilation on macOS

### ISSUE THREAD

**Issue by ymei** [StefanSchippers/xschem-gaw#10]
On macOS,
```
lib/sockcon.c
ttg/sockcon.c
```
need modification:
```
-#include <linux/tcp.h>
+#include <netinet/tcp.h>
```
It appears that `netinet/tcp.h` also exists on Linux.  Perhaps the source can simply be modified to use the `netinet/tcp.h` variant to work on both macOS and Linux?

**Comment by StefanSchippers** [comment]
I have committed your suggested fix. Thank you!
