### ISSUE TITLE
Fail to make

### ISSUE THREAD

**Issue by neilwang0913** [StefanSchippers/xschem-gaw#12]
gawimg.c:16:10: fatal error: 'gdk/gdkx.h' file not found

**Comment by StefanSchippers** [comment]
You need to install  package libgtk-3-dev, required to build the program.

**Comment by neilwang0913** [comment]
Hi Stefan: I am using the Mac OS. And I have try to install: brew install gtk+. But it fails. Any suggestion on that?

**Comment by StefanSchippers** [comment]
I don't have a Mac, however usually library packages come in bundles of 2: the library and the development files. Library is probably gtk+, there should be a gtk+-dev or something similar for the development files, these are needed to compile a program.
Also ensure gtk3 is used, as last release of gtk is gtk4 but this is not handled by gaw, it is a rather old application.

**Comment by StefanSchippers** [comment]
no followup. Closing.
