### ISSUE TITLE
variable list not available

### ISSUE THREAD

**Issue by Samarthjainabout** [StefanSchippers/xschem-gaw#14]
after successful simulation and launching gaw, I still cant see the variable list ?
<img width="1189" alt="Screenshot 2023-05-11 at 3 46 11 PM" src="https://github.com/StefanSchippers/xschem-gaw/assets/30805083/6ae064c5-85e2-4030-8cc7-12c0676e99b4">

**Comment by StefanSchippers** [comment]
do the following in your code block:
```
.control
  save all
  tran 0.01n 1u
  write transient.raw
.endc
```
