### ISSUE TITLE
./configure said: error: cannot find input file: `Makefile.in'

### ISSUE THREAD

**Issue by olisnr** [StefanSchippers/xschem-gaw#15]
the build was failing on my ubuntu 22.04. ./configure was saying: 
`checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in'
`

but i found a solution on the net:
`https://github.com/firnsy/yubipam/issues/1`

do this commands first: 

```
aclocal
autoconf
autoheader
automake --add-missing
./configure
```

`aclocal && automake --add-missing && autoconf` didnt helped me

may be we should the readme.md update

**Comment by StefanSchippers** [comment]
Ok I will update, looks more complete. Thank you!
