### ISSUE TITLE
Build Error "possibly undefined macro: AM_GNU_GETTEXT_VERSION"

### ISSUE THREAD

**Issue by ahmetenesturan** [StefanSchippers/xschem-gaw#16]
When I use `./configure`, I get the following error:

`config.status: error: cannot find input file: `Makefile.in'`

After using typing `aclocal`, I get these warnings:

`configure.ac:70: warning: macro 'AM_GNU_GETTEXT' not found in library`
`configure.ac:71: warning: macro 'AM_GNU_GETTEXT_VERSION' not found in library`

Using `autoconf` triggers the following errors:

`configure.ac:73: error: possibly undefined macro: AM_GNU_GETTEXT`
      `If this token and others are legitimate, please use m4_pattern_allow.`
      `See the Autoconf documentation.`
`configure.ac:74: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION`

After changing `GETTEXT_MACRO_VERSION = 0.22` and running `aclocal && automake --add-missing && autoconf`, `./configure` and `make` I get these errors:

```
gawmenus.c: In function ‘gm_create_layout’:
gawmenus.c:1227:14: error: assignment to ‘GMenuModel *’ {aka ‘struct _GMenuModel *’} from incompatible pointer type ‘GObject *’ {aka ‘struct _GObject *’} [-Wincompatible-pointer-types]
 1227 |    menumodel = g_object_ref (gtk_builder_get_object (builder,"menubar" ));
      |              ^
gawmenus.c:1235:18: error: assignment to ‘GMenuModel *’ {aka ‘struct _GMenuModel *’} from incompatible pointer type ‘GObject *’ {aka ‘struct _GObject *’} [-Wincompatible-pointer-types]
 1235 |    ud->algomodel = g_object_ref (gtk_builder_get_object (builder,"algomenu" ));
      |                  ^
gawmenus.c:1238:19: error: assignment to ‘GMenuModel *’ {aka ‘struct _GMenuModel *’} from incompatible pointer type ‘GObject *’ {aka ‘struct _GObject *’} [-Wincompatible-pointer-types]
 1238 |    ud->xconvmodel = g_object_ref (gtk_builder_get_object (builder,"xconvmenu" ));
      |                   ^
gawmenus.c:1241:17: error: assignment to ‘GMenuModel *’ {aka ‘struct _GMenuModel *’} from incompatible pointer type ‘GObject *’ {aka ‘struct _GObject *’} [-Wincompatible-pointer-types]
 1241 |    ud->vlmmodel = g_object_ref (gtk_builder_get_object (builder,"VarList" ));
      |                 ^
```

I am using Fedora 40 and my gettext version is 0.22.5-2.fc40.

**Comment by StefanSchippers** [comment]
Try to read this [readme](https://github.com/StefanSchippers/xschem-gaw/blob/main/README.md) to fix gnu automake/gettext issues.

I have had numerous problems with the GNU build system (too big, too complex, too slow and when it fails you are stuck) and this is the reason Xschem does not use it.

In particular try to reset the gettext version number:

> there is a gettext version mismatch between the expected one and the one installed on your system. edit the file po/Makefile.in.in and locate the following line:
> 
> GETTEXT_MACRO_VERSION = 0.20

and change it to 0.22.5-2.fc40 and cross fingers.
