### ISSUE TITLE
XSchem Command mode for schematic entry 

### ISSUE THREAD

**Issue by AhmedLilah** [StefanSchippers/xschem-gaw#9]
I'm looking to use xschem in command mode only but there doesn't seem to be a comprehensive doc for the commands .

if there is a doc for how to use command mode for schematic entry among all the other uses please refer to it. otherwise, your help will be very appreciated if you can make such a document.

**Comment by StefanSchippers** [comment]
Moved issue to [xschem](https://github.com/StefanSchippers/xschem/issues/59)
